dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [

    path('teste', views.teste, name='teste'),
    # Users
    path('user/create/', views.register_user, name='register_user'),
    path('login/', views.login_user, name='login'),
    path('login_or_register/', views.login_or_register, name='login_or_register'),
    path('user/logout/', views.logout_user, name='logout'),
    path('user/update/', views.user_update, name='user_update'),    

    # Dashboard
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # Agenda/CRUD    
    path('agendar/', views.agendar, name='agendar'), 
    path('agendar/<int:paciente_id>/', views.agendar_paciente, name='agendar_paciente'), 
    path('agendamento/<int:agendamento_id>/', views.read_agendamento, name='read_agendamento'), 
    path('agendamento/<int:agendamento_id>/update/',views.update_agendamento, name='update_agendamento'), 
    path('agendamento/<int:agendamento_id>/delete/',views.delete_agendamento, name='delete_agendamento'), 
    
    # Pacientes/CRUD/Search    
    path('pacientes/', views.pacientes, name='pacientes'),
    path('patient/create/', views.create, name='create'),
    path('patient/<int:paciente_id>/', views.read_patient, name='read_patient'),    
    path('patient/<int:paciente_id>/update/', views.update_patient, name='update_patient'),    
    path('patient/<int:paciente_id>/delete/', views.delete_patient, name='delete_patient'), 
    path('search_patient/', views.search_patient, name='search_patient'),

    # Prontuários/CRUD
    path('prontuarios/', views.prontuarios, name='prontuarios'),
    path('prontuarios/<int:paciente_id>/', views.prontuarios_especificos, name='prontuarios_especificos'),
    path('prontuario/<int:prontuario_id>/', views.read_prontuario, name='read_prontuario'),
    path('prontuario/<int:prontuario_id>/update/', views.update_prontuario, name='update_prontuario'),
    #path('prontuarios/<int:prontuario_id>/delete/', views.delete_prontuario,name='delete_prontuario'),    

    # Atendimento    
    path('atendimento/<int:agendamento_id>/', views.atendimento, name='atendimento'),
       
    
    # Configurações
    path('configuracoes/', views.configuracoes, name='configuracoes'),

    # Configurações/Convênios/CRUD

    path('convenios/', views.convenios, name='convenios'),
    path('convenio/create/', views.create_convenio, name='create_convenio'),
    path('convenio/<int:convenio_id>/', views.read_convenio, name='read_convenio'),
    path('convenio/update/<int:convenio_id>/', views.update_convenio, name='update_convenio'),
    path('convenio/delete/<int:convenio_id>/', views.delete_convenio, name='delete_convenio'),



]

sistema_medico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date
import re
from django.core.exceptions import ValidationError
from datetime import timedelta


class Procedimento(models.Model):
    nome = models.CharField(max_length=55)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.nome
    

class Convenio(models.Model):
    shared_choices = [
        ('Particular', 'Particular'),
        ('Unimed', 'Unimed'),
        ('SUS', 'SUS')
    ]
    shared_value = models.CharField(max_length=20, choices=shared_choices, default='Particular')    
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(max_length=55)
    valor_padrao = models.DecimalField(default=50.00, max_digits=10, decimal_places=2)
    n_reconsultas = models.CharField(max_length=10, default=3)
    prazo_reconsultas = models.CharField(max_length=30, default=15)

    def __str__(self):
        return self.nome
    

class Paciente(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    opcoes_sexo = [('Masculino', 'Masculino'),
                   ('Feminino', 'Feminino')]    
    nome = models.CharField(max_length=55)
    idade = models.CharField(max_length=2, blank=True, default=18)
    telefone = models.CharField(max_length=30)    
    data_criacao = models.DateTimeField(default=timezone.now)    
    observacao = models.TextField(blank=True)    
    show = models.BooleanField(default=True)
    email = models.EmailField(blank=True)
    data_nascimento = models.DateField(null=False)    
    sexo_biologico = models.CharField(max_length=10, choices=opcoes_sexo, null=False)
    cpf = models.CharField(max_length=14, null=False)
    rg = models.CharField(max_length=15, blank=True, default='')
    nome_mae = models.CharField(max_length=55, blank=True, default='')
    cep = models.CharField(max_length=20, blank=True, default='')
    endereco = models.CharField(max_length=20, blank=True, default='')
    numero = models.CharField(max_length=20, blank=True, default='')    
    bairro = models.CharField(max_length=20, blank=True, default='')    
    cidade = models.CharField(max_length=20, blank=True, default='')
    estado = models.CharField(max_length=20, blank=True, default='')
    
    def __str__(self):
        return self.nome

    def calcular_idade(self):
        hoje = date.today()
        return hoje.year - self.data_nascimento.year - ((hoje.month, hoje.day) < (self.data_nascimento.month, self.data_nascimento.day))    

    def save(self, *args, **kwargs):
        self.idade = self.calcular_idade()
        self.clean()  # Chama a função de validação antes de salvar
        super().save(*args, **kwargs)
    
class Agendamento(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    atendido = models.BooleanField(default=False)
    data_consulta = models.DateField(default='0000-00-00')
    hora_consulta = models.TimeField(default='09:00')
    procedimento = models.ForeignKey(Procedimento, on_delete=models.CASCADE)
    convenio = models.ForeignKey(Convenio, on_delete=models.CASCADE)
    opcoes_status = [('Pendente', 'Pendente'),
                     ('Cancelado', 'Cancelado'),
                     ('Confirmado', 'Confirmado')]
    status = models.CharField(max_length=20, choices=opcoes_status, default='Pendente')
    total_diario = models.IntegerField(default=0)
    total_mensal = models.IntegerField(default=0)
    total_anual = models.IntegerField(default=0)
    data_agendamento = models.DateTimeField(default=timezone.localdate())
    data_hora_agendamento = models.DateTimeField(default=timezone.now() - timedelta(hours=3) )

    def save(self, *args, **kwargs):        
        hoje = timezone.now()       
        
        if self.data_agendamento == hoje.date():
            self.total_diario += 1            
        else:
            self.total_diario = 1            

        if self.data_agendamento.month == hoje.month:
            self.total_mensal += 1            
        else:
            self.total_mensal = 1            

        if self.data_agendamento.year == hoje.year:
            self.total_anual += 1            
        else:
            self.total_anual = 1
            
        super().save(*args, **kwargs) 


    def data_formatada(self):
        return self.data_consulta.strftime('%d/%m/%y')



class Atendimento(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)     
    agendamento = models.ForeignKey(Agendamento, on_delete=models.CASCADE, null=True, blank=True)  
    atendido = models.BooleanField(default=False)
    queixa_principal = models.TextField(max_length=20, blank=True, null=True)
    historia_molestia_atual = models.TextField(max_length=250, blank=True)
    historico_e_antecedentes = models.TextField(max_length=200, blank=True)
    exame_fisico = models.TextField(max_length=250, blank=True)
    altura = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)# Altura em metros
    peso = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)# Peso em quilogramas
    imc = models.FloatField(null=True, blank=True)
    diagnostico = models.TextField(max_length=50, blank=True)
    condutas = models.TextField(max_length=250, blank=True)
    total_diario = models.IntegerField(default=0)
    total_mensal = models.IntegerField(default=0)
    total_anual = models.IntegerField(default=0)
    data_atendimento = models.DateField(default=timezone.localdate)
    data_hora_atendimento = models.DateTimeField(default=timezone.now())
    editado = models.BooleanField(default=False)
    valor_total_diario = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    valor_total_mensal = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    valor_total_anual = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    
    

    def save(self, *args, **kwargs):        
        hoje = timezone.now()        
        
        if self.editado == False:
            if self.data_atendimento == hoje.date:
                self.total_diario += 1                
            else:
                self.total_diario = 1
                

            if self.data_atendimento.month == hoje.month:
                self.total_mensal += 1                
            else:
                self.total_mensal = 1
                

            if self.data_atendimento.year == hoje.year:
                self.total_anual += 1                
            else:
                self.total_anual = 1

        if self.agendamento.procedimento.nome == 'Consulta':
            if self.data_atendimento == hoje.date:
                self.valor_total_diario += self.agendamento.convenio.valor_padrao
            else:
                self.valor_total_diario = self.agendamento.convenio.valor_padrao

            if self.data_atendimento == hoje.month:
                self.valor_total_mensal += self.agendamento.convenio.valor_padrao
            else:
                self.valor_total_mensal = self.agendamento.convenio.valor_padrao
            
            if self.data_atendimento == hoje.year:
                self.valor_total_anual += self.agendamento.convenio.valor_padrao
            else:
                self.valor_total_anual = self.agendamento.convenio.valor_padrao
                
        super().save(*args, **kwargs)      

    












    
    

dashboard/views.py
from django.shortcuts import render

app_name = 'index'


def index(request):
    return render(request, 'index.html')

dashboard/views/teste.py
from django.shortcuts import render
from django import forms
from dashboard.models import Atendimento
from django.core.exceptions import ValidationError

class TesteForm(forms.ModelForm):
    class Meta:
        model = Atendimento
        fields =  'queixa_principal', 'historia_molestia_atual', 'historico_e_antecedentes', \
                 'exame_fisico', 'altura', 'peso', 'diagnostico', 'condutas',

    def clean(self):
        cleaned_data = self.cleaned_data
        
        self.add_error(
            'queixa_principal',
            ValidationError(
                'Mensagem de erro',
                code='invalid'
            )
        )

        return super().clean()

def teste(request):
    if request.method == 'POST':
        context = {
        'form' : TesteForm(request.POST)
        }
    
        return render(request, 'teste.html', context)

    context = {
            'form' : TesteForm()
        }
    return render(request, 'teste.html', context)

dashboard/views/v_index.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from dashboard.models import Paciente
from django.utils import timezone
from django.core.paginator import Paginator

#o Q é uma função para poder utilizar o '|' que faz a função de 'or' e não 'and' na consulta sql

app_name = 'index'


def index(request):
    data_hora_atual = timezone.now()

    pacientes = Paciente.objects\
        .filter(show=True)\
        .filter(data_consulta__gte=data_hora_atual)\
        .order_by('data_consulta', 'hora_consulta')
    
    paginator = Paginator(pacientes, 7)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj' : page_obj,
    }

    return render(request, 'dashboard/index.html', context)


def search(request):

    search_value = request.GET.get('q', '').strip()
    data_hora_atual = timezone.now()

    if search_value == '':
        return redirect('dashboard:index')    

    pacientes = Paciente.objects\
        .filter(show=True)\
        .filter(data_consulta__gte=data_hora_atual)\
        .filter(
            Q(nome__icontains=search_value)|
            Q(convenio__nome__icontains=search_value)|             
            Q(procedimento__nome__icontains=search_value)
            )\
        .order_by('data_consulta', 'hora_consulta')
    
    paginator = Paginator(pacientes, 7)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj' : page_obj,
        'site_title' : 'Search - ',
        'search_value' : search_value,
    }

    return render(request, 'index.html', context)

dashboard/templates/pacientes/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content">
    {% include 'partials/_messages.html' %}
    
    <div class="titulo-secao">
        
        <div class="form_patient">
            
            <h1>{{ nome_func }}</h1>
            
            <form
                action="{{ form_action }}"
                method="POST" class="form-create-patient">
                {% csrf_token %}
                
                
                {% for field in form %}
                <div class="form-field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                    {{ field.errors }}
                </div>

                {% endfor %}
                {% for error in form.email.errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}

                <input type="submit" value="Enviar">
            </form>
        </div>
    </div>
</div>

<script src="{% static 'static/js/data_nascimento_format.js' %}"></script>
<script src="{% static 'static/js/telefone_format.js' %}"></script>
<script src="{% static 'static/js/cpf_format.js' %}"></script>
{% endblock %}

dashboard/templates/pacientes/pacientes.html
{% extends 'base.html' %}

{% block content %}  

<div class="content">
    <div class="btns-main ">     
        
        <a class="btn-main" href="{% url 'dashboard:create' %}">
            <i class="fa-regular fa-plus"></i>
            Registrar novo Paciente</a>
        <a class="btn-main" href="{% url 'dashboard:agendar' %}">
            <i class="fa-regular fa-calendar"></i>
            Agendar um Paciente</a>
    </div>   

    {% if page_obj %}        
        <div class="table-container">
            <div class="message-center">{% include 'partials/_messages.html' %}</div>            
            <table class="table-index">                       
                <thead class="table-head">  
                    <tr class="table-row">
                        <th colspan="7"> 
                            <h3 class="titulo-consultas">Pacientes </h3>
                        </th>
                    </tr>                                        
                    <tr class="table-row">                        
                        <th>Nome</th>
                        <th>ID</th>
                        <th>Telefone</th>
                        <th>Última consulta</th>                       
                    </tr>
                </thead>
                <tbody>
                    {% for p in page_obj %}           
                        <tr class="table-row">                        
                            <td>
                                <a href="{% url 'dashboard:read_patient' p.id %}">
                                    {{ p.nome }}
                                </a>
                            </td>

                            <td>
                                <a href="{% url 'dashboard:read_patient' p.id %}">
                                    {{ p.id }}
                                </a>
                            </td> 
                            <td>{{ p.telefone}}</td>
                            <td> {{ p.ultimo_atendimento }}</td>
                            <td>                                
                                <a class="btn-main" href="{% url 'dashboard:agendar_paciente' p.id %}">Agendar</a>
                                <a class="btn-main" href="{% url 'dashboard:prontuarios_especificos' p.id %}">Prontuarios</a>
                            </td>
                        </tr>
                    {% endfor %}  
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">
                            {% include 'partials/_pagination.html' %} 
                        </td>
                    </tr>
                </tfoot>
            </table>
             
        </div> 
        {% else %}
        <div class="titulo-secao">
            <h2>
                Nenhum paciente registrado.
            </h2>
        </div>
    {% endif %}
</div>
{% endblock %}
                                                       

dashboard/templates/pacientes/read_patient.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <div class="read-patient">  
        {% include 'partials/_messages.html' %}     
        <h1>{{ paciente.nome }} </h1>  
        <br>              
        <h2>Idade: {{ paciente.idade }}</h2>
        <h2>Sexo: {{paciente.sexo_biologico}}</h2> 
        <h2>CPF: {{paciente.cpf}}</h2>
        <h2>Telefone:{{paciente.telefone}}</h2> 
        <br>   
        <h2>RG:{{paciente.rg}}</h2>  
        <h2>Email:{{paciente.email}}</h2>  
        <h2>CEP:{{paciente.cep}}</h2> 
        <h2>Endereço:{{paciente.endereco}}</h2>     
        <h2>Número:{{paciente.numero}}</h2> 
        <h2>Bairro:{{paciente.bairro}}</h2>     
        <h2>Cidade:{{paciente.cidade}}</h2>     
        <h2>Estado:{{paciente.estado}}</h2>    
        
         
    </div>

    <div class="btns-ud">
        <a class="btn-edit-patient" href="{% url 'dashboard:update_patient' paciente.id %}">
            Editar
        </a>    
    
        <form class="btn-delete-patient" action="{% url 'dashboard:delete_patient' paciente.id %}" method="POST">
            {% csrf_token %}
            <a class="btn-delete-patient" href="{% url 'dashboard:delete_patient' paciente.id %}">
                Deletar
            </a>
        </form>
    </div>


</div>
{% endblock %}
    